export MESONET_DLC_PROJECT_DIR=

export BDBC_SESSION_ROOT=
export BDBC_RAWDATA_ROOT=
export BDBC_MESOSCALER_ROOT=
export BDBC_VIDEOS_ROOT=

export BDBC_BODYMODEL_DIR=
export BDBC_FACEMODEL_DIR=
export BDBC_EYEMODEL_DIR=

export BDBC_BODYRESULTS_ROOT=
export BDBC_FACERESULTS_ROOT=
export BDBC_EYERESULTS_ROOT=
export BDBC_PUPILFITTING_ROOT=

export BDBC_PUBLICATION_ROOT=

