export DLC_EYEMODEL_DIR=
export DLC_FACEMODEL_DIR=
export DLC_BODYMODEL_DIR=
export MESONET_DLC_PROJECT_DIR=

export SESSIONS_ROOT_DIR=
export RAWDATA_ROOT_DIRS=
export MESOSCALER_ROOT_DIR=
export VIDEOS_ROOT_DIR=
export DLCRESULTS_ROOT_DIR=
export PUPILFITTING_ROOT_DIR=
export PUBLICATION_ROOT_DIR=

